version: 1

project_name: octo
dist: bin
builds:
  - id: octo
    main: ./cmd/octo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    builds: [octo]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE.txt
      - README.md

release:
  github:
    owner: gdegiorgio
    name: octo
changelog:
  use: git
