version: 2

project_name: octo
dist: bin
builds:
  - id: octo
    main: ./cmd/octo
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: octo-win
    main: ./cmd/octo
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    ids: [octo]
    formats: [tar.gz]
    name_template: "octo_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE.txt
      - README.md
  - id: octo-win
    ids: [octo-win]
    formats: [zip]
    name_template: "octo_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE.txt
      - README.md

release:
  github:
    owner: gdegiorgio
    name: octo
changelog:
  use: git
