name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: 🔨 Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Install dependencies
        run: go mod tidy

      - name: Lint code
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Build project
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
